Use logService for console messages
bitwarden/desktop pull request #602
Opened 2020-11-30 23:09 UTC by MGibson1

This PR is associated with issue bitwarden/cli/issues/188 and bitwarden/jslib#214

# Objective

Specify use of electron log service for console jslib-handled console logging

# Files Changed
* **services.module.ts**: included logService optional parameter on service constructors

# Draft reason
**This PR needs to merge after bitwarden/jslib#214 and update jslib's submodule reference**

2020-12-04 21:14 UTC, cscharf approved these changes

2020-12-09 21:13 UTC, cscharf requested changes
Likely need to reverse/undo these changes.

2020-12-09 21:21 UTC, MGibson1 commented
the jslib dependency, yeah

2020-12-09 21:24 UTC, cscharf commented
> the jslib dependency, yeah. Or are you specifying all of them?

Nope, just the jslib dependency, sorry, should have been more specific

2020-12-14 17:34 UTC, cscharf approved these changes

2020-12-14 17:57 UTC, merged