Add missing languages from Crowdin
bitwarden/desktop pull request #897
Opened 2021-05-14 20:43 UTC by tgreer-bw

Langauge updates for Desktop

2021-05-14 22:15 UTC, cscharf approved these changes

2021-05-14 22:17 UTC, cscharf requested changes
Looks like an errant single quote

2021-05-14 22:17 UTC, cscharf commented on src/services/i18n.service.ts
> +            'en', 'af, ''be', 'bg', 'bn', 'ca', 'cs', 'da', 'de', 'el', 'en-GB', 'en-IN', 'es', 'et', 'fa', 'fi', 'fr', 'he', 'hr', 'hu', 'id',
```suggestion
            'en', 'af', 'be', 'bg', 'bn', 'ca', 'cs', 'da', 'de', 'el', 'en-GB', 'en-IN', 'es', 'et', 'fa', 'fi', 'fr', 'he', 'hr', 'hu', 'id',
```

2021-05-14 22:59 UTC, tgreer-bw commented
All fixed! Thanks for catching that.

2021-05-15 19:25 UTC, cscharf approved these changes

2021-05-15 19:25 UTC, merged