Use password field with toggle to set PIN
bitwarden/desktop pull request #964
Opened 2021-06-22 04:49 UTC by eliykat

## Objective

Desktop implementation of https://github.com/bitwarden/browser/pull/1911. They're identical, so I'll duplicate any code review changes across both PRs.

2021-06-22 08:46 UTC, Hinton requested changes
We need to sanitize any dynamic value in the `innerHTML`.

2021-06-22 08:46 UTC, Hinton commented on src/app/accounts/settings.component.ts
> +                        placeholder="${this.i18nService.t('pin')}">
Sanitize.

2021-06-23 00:00 UTC, eliykat commented
Waiting to see if I can use an Angular component instead, per bitwarden/jslib#417

2021-09-07 07:19 UTC, eliykat commented
Closing this, will reopen new PR using dynamic modals.

2021-09-07 07:19 UTC, closed without merging